openapi: 3.0.0
info:
  title: Users API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Liste des utilisateurs
      parameters:
        - name: page
          in: query
          schema:
            type: integer
        - name: size
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Liste d'utilisateurs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
              example:
                - id: 1
                  name: Fiderana
                  email: hei.fiderana@gmail.com
        '400':
          description: Mauvais paramètres
          content:
            application/json:
              example:
                error: Bad types for provided query parameters
